import cron from "node-cron";
import { autoGenerateDriverInvoice } from "./autoGenerateDriverInvoice.js";
import CronJob from "../../models/settings/CronJob.js";

export const scheduleDriverStatements = () => {
  cron.schedule(
    "* * * * *",
    async () => {
      console.log("[CRON] Running driver statements check");

      try {
        const companies = await CronJob.find({
          "driverStatement.enabled": true,
          "driverStatement.notifications.email": true,
        });

        for (const job of companies) {
          await autoGenerateDriverInvoice(job.companyId);
        }
      } catch (err) {
        console.error("[CRON] Driver statements failed:", err);
      }
    },
    {
      timezone: process.env.CRON_TIMEZONE || "UTC",
    }
  );
};