import Icons from "../../assets/icons";

const sidebarItems = [
  {
    title: "Home",
    icon: Icons.Home,
    route: "/dashboard/home",
  },
  {
    title: "Bookings",
    icon: Icons.ScrollText,
    route: "/dashboard/bookings",
    subTabs: [
      {
        title: "Bookings List",
        route: "/dashboard/bookings/list",
        icon: Icons.ListChecks,
      },
      {
        title: "New Booking",
        route: "/dashboard/bookings/new",
        icon: Icons.PlusCircle,
        roles: ["clientadmin", "manager"],
      },
      {
        title: "Booking Calendar",
        route: "/dashboard/bookings/calendar",
        icon: Icons.CalendarDays,
      },
      {
        title: "Deleted Booking",
        route: "/dashboard/bookings/deleted-booking",
        icon: Icons.Delete,
        roles: ["clientadmin", "manager", "associateadmin", "superadmin"],
      },
    ],
  },
  {
    title: "Invoices",
    icon: Icons.FileText,
    route: "/dashboard/invoices",
    subTabs: [
      {
        title: "Invoices List",
        route: "/dashboard/invoices/list",
        icon: Icons.List,
        roles: [
          "driver",
          "superadmin",
          "manager",
          "associateadmin",
          "customer",
          "clientadmin",
        ],
      },
      {
        title: "New Driver Invoice",
        route: "/dashboard/invoices/driver/new",
        icon: Icons.FilePlus,
        roles: ["clientadmin", "manager", "associateadmin", "superadmin"],
      },
      {
        title: "New Customer Invoice",
        route: "/dashboard/invoices/customer/new",
        icon: Icons.FilePlus,
        roles: ["clientadmin", "superadmin", "manager", "associateadmin"],
      },
    ],
  },
  {
    title: "Drivers",
    icon: Icons.Users,
    route: "/dashboard/drivers",
    subTabs: [
      {
        title: "Driver List",
        route: "/dashboard/drivers/list",
        icon: Icons.List,
        roles: [
          "driver",
          "superadmin",
          "clientadmin",
          "associateadmin",
          "manager",
        ],
      },
      {
        title: "New Driver",
        route: "/dashboard/drivers/new",
        icon: Icons.UserPlus,
        roles: [
          "driver",
          "superadmin",
          "clientadmin",
          "associateadmin",
          "manager",
        ],
      },
      // {
      //   title: "Registration Config",
      //   route: "/dashboard/drivers/config",
      //   icon: Icons.Settings2,
      // },
      {
        title: "Rides",
        icon: Icons.CarFront,
        route: "/dashboard/drivers/all-rides",
        roles: ["driver", "superadmin", "manager"],
      },
      {
        title: "Earnings",
        icon: Icons.Activity,
        route: "/dashboard/drivers/earnings",
        roles: ["driver", "superadmin", "manager"],
      },
    ],
  },
  {
    title: "Customers",
    icon: Icons.UsersRound,
    route: "/dashboard/customers",
    subTabs: [
      {
        title: "Customers List",
        route: "/dashboard/customers/list",
        icon: Icons.List,
        roles: ["clientadmin", "associateadmin", "superadmin", "manager"],
      },
    ],
  },
  {
    title: "Company Accounts",
    icon: Icons.Building,
    route: "/dashboard/company-accounts",
    subTabs: [
      {
        title: "Accounts List",
        route: "/dashboard/company-accounts/list",
        icon: Icons.FileText,
        roles: ["superadmin", "clientadmin", "associateadmin", "manager"],
      },
      {
        title: "Add Account",
        route: "/dashboard/company-accounts/new",
        icon: Icons.PlusCircle,
        roles: ["superadmin", "manager", "clientadmin"],
      },
      {
        title: "View Company",
        route: "/dashboard/view-company",
        icon: Icons.Building2,
        roles: [
          "driver",
          "superadmin",
          "customer",
          "clientadmin",
          "associateadmin",
          "manager",
        ],
      },
    ],
  },
  {
    title: "Statements",
    icon: Icons.FileText,
    route: "/dashboard/statements",
    subTabs: [
      {
        title: "Driver Statements",
        route: "/dashboard/statements/driver",
        icon: Icons.Truck,
        roles: [
          "driver",
          "superadmin",
          "clientadmin",
          "associateadmin",
          "manager",
        ],
      },
      {
        title: "Driver Payments",
        route: "/dashboard/statements/payments",
        icon: Icons.CreditCard,
        roles: [
          "driver",
          "superadmin",
          "clientadmin",
          "associateadmin",
          "manager",
          "driver",
        ],
      },
    ],
  },
  {
    title: "Users",
    icon: Icons.Users,
    route: "/dashboard/admin-list",
    subTabs: [
      {
        title: "Admin List",
        icon: Icons.List,
        route: "/dashboard/admin-list",
        roles: ["superadmin", "clientadmin", "associateadmin", "manager"],
      },
      {
        title: "New  User",
        icon: Icons.User,
        route: "/dashboard/admin-list/create-admin-user",
        roles: ["superadmin", "clientadmin", "associateadmin", "manager"],
      },
    ],
  },
  {
    title: "Pricing",
    icon: Icons.DollarSign,
    route: "/dashboard/pricing",
    subTabs: [
      {
        title: "General",
        route: "/dashboard/pricing/general",
        icon: Icons.Settings,
        roles: ["clientadmin", "associateadmin", "superadmin", "manager"],
      },
      {
        title: "Vehicle Pricing",
        route: "/dashboard/pricing/vehicle",
        icon: Icons.Truck,
        roles: ["clientadmin", "associateadmin", "superadmin", "manager"],
      },
      {
        title: "Distance Slab",
        route: "/dashboard/pricing/distance-slab",
        icon: Icons.Activity,
        roles: ["clientadmin", "associateadmin", "superadmin", "manager"],
      },
      {
        title: "Hourly Packages",
        route: "/dashboard/pricing/hourly-packages",
        icon: Icons.Clock,
        roles: ["clientadmin", "associateadmin", "superadmin", "manager"],
      },
      {
        title: "Fixed Pricing",
        route: "/dashboard/pricing/fixed",
        icon: Icons.Tag,
        roles: ["clientadmin", "associateadmin", "superadmin", "manager"],
      },
      {
        title: "Postcode District",
        route: "/dashboard/pricing/postcode-district",
        icon: Icons.Map,
        roles: ["clientadmin", "associateadmin", "superadmin", "manager"],
      },
      {
        title: "Zones",
        route: "/dashboard/pricing/zones",
        icon: Icons.Grid,
        roles: ["clientadmin", "associateadmin", "superadmin", "manager"],
      },
      {
        title: "Discounts / Surcharge - Date",
        route: "/dashboard/pricing/discounts-date",
        icon: Icons.Calendar,
        roles: ["clientadmin", "associateadmin", "superadmin", "manager"],
      },
      {
        title: "Vouchers",
        route: "/dashboard/pricing/vouchers",
        icon: Icons.Gift,
        roles: ["clientadmin", "associateadmin", "superadmin", "manager"],
      },
    ],
  },

  {
    title: "Settings",
    icon: Icons.Settings,
    route: "/dashboard/settings",
    subTabs: [
      {
        title: "General",
        route: "/dashboard/settings/general",
        icon: Icons.Sliders,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },

      {
        title: "Booking",
        route: "/dashboard/settings/booking",
        icon: Icons.Book,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Email",
        route: "/dashboard/settings/email",
        icon: Icons.Mail,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Location Category",
        route: "/dashboard/settings/location-category",
        icon: Icons.MapPin,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Notifications",
        route: "/dashboard/settings/notifications",
        icon: Icons.Bell,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Locations",
        route: "/dashboard/settings/locations",
        icon: Icons.Map,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Coverage",
        route: "/dashboard/settings/coverage",
        icon: Icons.Globe,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Payment Options",
        route: "/dashboard/settings/payment-options",
        icon: Icons.CreditCard,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Booking Restriction Date",
        route: "/dashboard/settings/booking-restriction-date",
        icon: Icons.CalendarX,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Review",
        route: "/dashboard/settings/review",
        icon: Icons.Star,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Receipt",
        route: "/dashboard/settings/receipt",
        icon: Icons.Receipt,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Notifications Settings",
        route: "/dashboard/settings/settings-notifications",
        icon: Icons.Bell,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Google Calendar",
        route: "/dashboard/settings/google-calendar",
        icon: Icons.Calendar,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "SMS",
        route: "/dashboard/settings/sms",
        icon: Icons.MessageSquare,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Social Media",
        route: "/dashboard/settings/social-media",
        icon: Icons.Share2,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Chat Plugin",
        route: "/dashboard/settings/chat-plugin",
        icon: Icons.MessageCircle,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Cron Job",
        route: "/dashboard/settings/cron-job",
        icon: Icons.Clock,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Driver Contact",
        route: "/dashboard/settings/driver-contact",
        icon: Icons.Clock,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
      {
        title: "Terms and Condition",
        route: "/dashboard/settings/terms-and-condition",
        icon: Icons.Clock,
        roles: [
          "clientadmin",
          "associateadmin",
          "superadmin",
          "manager",
          "driver",
        ],
      },
    ],
  },
  {
    title: "Widget/API",
    icon: Icons.Code,
    route: "/dashboard/widget-api",
    roles: ["clientadmin", "associateadmin", "superadmin", "manager"],
  },
  {
    title: "Profile",
    icon: Icons.User,
    route: "/dashboard/profile",
  },
  {
    title: "Logout",
    icon: Icons.LogOut,
    route: "/dashboard/logout",
  },
];

export default sidebarItems;
